"""finalized_at and needs_human_review

Revision ID: 4e8077f0c08d
Revises: 4d5ca47416ab
Create Date: 2026-07-10 14:00:43.107137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e8077f0c08d"
down_revision: Union[str, Sequence[str], None] = "4d5ca47416ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_versions", sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("contract_versions", sa.Column("needs_human_review", sa.Boolean(), nullable=True))
    op.create_index(
        "uq_contract_versions_one_final",
        "contract_versions",
        ["contract_id"],
        unique=True,
        postgresql_where=sa.text("finalized_at IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_contract_versions_one_final",
        table_name="contract_versions",
        postgresql_where=sa.text("finalized_at IS NOT NULL"),
    )
    op.drop_column("contract_versions", "needs_human_review")
    op.drop_column("contract_versions", "finalized_at")
    # ### end Alembic commands ###
