"""memory facts and conversation summaries

Revision ID: 93cfdaed7c8c
Revises: a4edecc1901f
Create Date: 2026-07-13 12:15:34.717141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93cfdaed7c8c"
down_revision: Union[str, Sequence[str], None] = "a4edecc1901f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("stability", sa.String(length=16), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("forgotten_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'user_confirmed' AND confidence = 1.0) OR (source = 'carried_forward' AND confidence < 1.0)",
            name="ck_memory_facts_confidence_matches_source",
        ),
        sa.CheckConstraint(
            "source IN ('user_confirmed', 'carried_forward')", name="ck_memory_facts_source"
        ),
        sa.CheckConstraint("stability IN ('stable', 'volatile')", name="ck_memory_facts_stability"),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["memory_facts.id"],
            ondelete="SET NULL",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_memory_facts_live",
        "memory_facts",
        ["tenant_id", "user_id", "key"],
        unique=True,
        postgresql_where=sa.text("superseded_by IS NULL AND forgotten_at IS NULL"),
    )
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("turns_covered", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_summaries")
    op.drop_index(
        "uq_memory_facts_live",
        table_name="memory_facts",
        postgresql_where=sa.text("superseded_by IS NULL AND forgotten_at IS NULL"),
    )
    op.drop_table("memory_facts")
    # ### end Alembic commands ###
